name: DeadFatigue
version: '1.0'
main: ltd.teaparty.deadfatigue.DeadFatigue
api-version: '1.20'
depend: [PlayerFatigue]
commands:
  deadfatigue:
    description: reload plugin
    permission: deadfatigue.reload
